DROP DOMAIN IF EXISTS sex_tag CASCADE; 
CREATE DOMAIN sex_tag AS CHAR
CHECK(
	VALUE = 'M'
	OR VALUE = 'F'
	OR VALUE = 'U'
);

DROP DOMAIN IF EXISTS label_tag CASCADE;
CREATE DOMAIN label_tag AS CHAR
CHECK(
	VALUE = 'D'
	OR VALUE = 'L'
	OR VALUE = 'U'
);